// Generated from OpenAPI/Swagger specification
// Do not edit directly

/**
 * Shared types for Medication Management application
 * Generated from OpenAPI/Swagger
 */

// Export API client generated from OpenAPI/Swagger
export * from './api-client';

// Utility types that might still be needed but aren't generated by Swagger
export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  error?: string;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}

export interface DashboardStats {
  totalRecipients: number;
  totalMedications: number;
  totalSchedules: number;
  upcomingDoses: number;
  takenDoses: number;
  missedDoses: number;
}

export interface AuthResponse {
  user: {
    id: string;
    email: string;
    firstName: string;
    lastName: string;
    role: string;
  };
  token: string;
}

// Export DoseStatus enum which might be used in the frontend
export type DoseStatus = 'scheduled' | 'taken' | 'missed';
