AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  medication-management-api

  Medication Management API for HomeThrive

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Tracing: Active
    Environment:
      Variables:
        NODE_OPTIONS: --enable-source-maps
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

Resources:
  # Database resources
  DatabaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Medication Management API database
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2

  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Medication Management API database
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref LambdaSecurityGroup

  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Medication Management API Lambda functions
      VpcId: !Ref VPC

  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: medication_management
      Engine: postgres
      EngineVersion: 14.5
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      StorageType: gp2
      MasterUsername: !Sub '{{resolve:secretsmanager:${DatabaseSecret}:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${DatabaseSecret}:SecretString:password}}'
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      VPCSecurityGroups:
        - !Ref DatabaseSecurityGroup
      BackupRetentionPeriod: 7
      MultiAZ: false
      PubliclyAccessible: false
      StorageEncrypted: true
      DeletionProtection: false
      Tags:
        - Key: Environment
          Value: !Ref Environment

  DatabaseSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'medication-management-db-credentials-${Environment}'
      Description: RDS database credentials
      GenerateSecretString:
        SecretStringTemplate: '{"username": "postgres"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  # VPC resources
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub 'medication-management-vpc-${Environment}'

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub 'medication-management-private-subnet-1-${Environment}'

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub 'medication-management-private-subnet-2-${Environment}'

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub 'medication-management-public-subnet-1-${Environment}'

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.4.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub 'medication-management-public-subnet-2-${Environment}'

  # Lambda functions
  JWTAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: authorizer.handler
      Runtime: nodejs20.x
      Environment:
        Variables:
          JWT_SECRET: !Sub '{{resolve:secretsmanager:${JwtSecret}:SecretString:secret}}'

  MedicationManagementFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Layers:
        - !Ref PrismaLayer
      Architectures:
        - x86_64
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
      Environment:
        Variables:
          DATABASE_URL: !Sub 
            - 'postgresql://postgres:{{resolve:secretsmanager:${SecretId}:SecretString:password}}@${DatabaseHost}:5432/medication_management'
            - SecretId: !Ref DatabaseSecret
              DatabaseHost: !Ref DatabaseHost
          JWT_SECRET: !Sub '{{resolve:secretsmanager:${JwtSecret}:SecretString:secret}}'
          IS_LOCAL: 'false'
          NODE_ENV: !Ref Environment
      Events:
        # Public endpoints (no auth)
        HealthCheck:
          Type: Api
          Properties:
            Path: /health
            Method: get
        Register:
          Type: Api
          Properties:
            Path: /auth/register
            Method: post
        Login:
          Type: Api
          Properties:
            Path: /auth/login
            Method: post

        # Protected endpoints (with auth)
        Profile:
          Type: Api
          Properties:
            Path: /auth/profile
            Method: get
            Auth:
              Authorizer: JWTAuthorizerFunction

        # Medication endpoints
        GetMedications:
          Type: Api
          Properties:
            Path: /medications
            Method: get
            Auth:
              Authorizer: JWTAuthorizerFunction
        CreateMedication:
          Type: Api
          Properties:
            Path: /medications
            Method: post
            Auth:
              Authorizer: JWTAuthorizerFunction
        GetMedication:
          Type: Api
          Properties:
            Path: /medications/{id}
            Method: get
            Auth:
              Authorizer: JWTAuthorizerFunction
        UpdateMedication:
          Type: Api
          Properties:
            Path: /medications/{id}
            Method: put
            Auth:
              Authorizer: JWTAuthorizerFunction
        DeleteMedication:
          Type: Api
          Properties:
            Path: /medications/{id}
            Method: delete
            Auth:
              Authorizer: JWTAuthorizerFunction

        # Dose endpoints
        GetDoses:
          Type: Api
          Properties:
            Path: /doses
            Method: get
            Auth:
              Authorizer: JWTAuthorizerFunction
        GetDose:
          Type: Api
          Properties:
            Path: /doses/{id}
            Method: get
            Auth:
              Authorizer: JWTAuthorizerFunction
        UpdateDoseStatus:
          Type: Api
          Properties:
            Path: /doses/{id}/status
            Method: put
            Auth:
              Authorizer: JWTAuthorizerFunction

        # Dashboard endpoints
        GetUpcomingDoses:
          Type: Api
          Properties:
            Path: /dashboard/upcoming-doses
            Method: get
            Auth:
              Authorizer: JWTAuthorizerFunction
        GetDashboardStats:
          Type: Api
          Properties:
            Path: /dashboard/stats
            Method: get
            Auth:
              Authorizer: JWTAuthorizerFunction

        # Care Recipient endpoints
        GetCareRecipients:
          Type: Api
          Properties:
            Path: /care-recipients
            Method: get
            Auth:
              Authorizer: JWTAuthorizerFunction
        CreateCareRecipient:
          Type: Api
          Properties:
            Path: /care-recipients
            Method: post
            Auth:
              Authorizer: JWTAuthorizerFunction
        GetCareRecipient:
          Type: Api
          Properties:
            Path: /care-recipients/{id}
            Method: get
            Auth:
              Authorizer: JWTAuthorizerFunction
        UpdateCareRecipient:
          Type: Api
          Properties:
            Path: /care-recipients/{id}
            Method: put
            Auth:
              Authorizer: JWTAuthorizerFunction
        DeleteCareRecipient:
          Type: Api
          Properties:
            Path: /care-recipients/{id}
            Method: delete
            Auth:
              Authorizer: JWTAuthorizerFunction

        # Schedule endpoints
        GetSchedules:
          Type: Api
          Properties:
            Path: /schedules
            Method: get
            Auth:
              Authorizer: JWTAuthorizerFunction
        CreateSchedule:
          Type: Api
          Properties:
            Path: /schedules
            Method: post
            Auth:
              Authorizer: JWTAuthorizerFunction
        GetSchedule:
          Type: Api
          Properties:
            Path: /schedules/{id}
            Method: get
            Auth:
              Authorizer: JWTAuthorizerFunction
        UpdateSchedule:
          Type: Api
          Properties:
            Path: /schedules/{id}
            Method: put
            Auth:
              Authorizer: JWTAuthorizerFunction
        DeleteSchedule:
          Type: Api
          Properties:
            Path: /schedules/{id}
            Method: delete
            Auth:
              Authorizer: JWTAuthorizerFunction
      Policies:
        - VPCAccessPolicy: {}
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref DatabaseSecret
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref JwtSecret
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts
        External:
          - "@prisma/client"

  JwtSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'medication-management-jwt-secret-${Environment}'
      Description: JWT secret for authentication
      GenerateSecretString:
        SecretStringTemplate: '{"secret": ""}'
        GenerateStringKey: "secret"
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

  # Application monitoring
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

  # Add the Prisma Layer
  PrismaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: prisma-layer
      Description: Prisma ORM Layer
      ContentUri: layers/prisma/
      CompatibleRuntimes:
        - nodejs20.x
      RetentionPolicy: Retain

Outputs:
  MedicationManagementApi:
    Description: API Gateway endpoint URL for Prod stage for Medication Management API
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  
  MedicationManagementFunction:
    Description: Medication Management Lambda Function ARN
    Value: !GetAtt MedicationManagementFunction.Arn
  
  MedicationManagementFunctionIamRole:
    Description: Implicit IAM Role created for Medication Management function
    Value: !GetAtt MedicationManagementFunctionRole.Arn
  
  DatabaseEndpoint:
    Description: RDS Database Endpoint
    Value: !GetAtt DatabaseInstance.Endpoint.Address
